# Pushing this code to Container Registry
# steps:
#   # Building Docker image for flask-app-1
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/flask-app-1:$SHORT_SHA'
#       - '-f'
#       - 'app1/Dockerfile'
#       - 'app1/'

#   # Building Docker image for flask-app-2
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/flask-app-2:$SHORT_SHA'
#       - '-f'
#       - 'app2/Dockerfile'
#       - 'app2/'

#   # Pushing Docker image for flask-app-1 to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'push'
#       - 'gcr.io/$PROJECT_ID/flask-app-1:$SHORT_SHA'

#   # Pushing Docker image for flask-app-2 to Container Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'push'
#       - 'gcr.io/$PROJECT_ID/flask-app-2:$SHORT_SHA'

# # List of Docker images to track
# images:
#   - 'gcr.io/$PROJECT_ID/flask-app-1:$SHORT_SHA'
#   - 'gcr.io/$PROJECT_ID/flask-app-2:$SHORT_SHA'

# # Build options and environment variables
# options:
#   env:
#     - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'

# # Logs bucket configuration
# logsBucket: ncorium-bucket


# Pushing this code to Artifact Registory
# steps:
#   # Building Docker image for flask-app-1
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-t'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-1:$SHORT_SHA'
#       - '-f'
#       - 'app1/Dockerfile'
#       - 'app1/'

#   # Building Docker image for flask-app-2
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-t'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-2:$SHORT_SHA'
#       - '-f'
#       - 'app2/Dockerfile'
#       - 'app2/'

#   # Pushing Docker image for flask-app-1 to Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'push'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-1:$SHORT_SHA'

#   # Pushing Docker image for flask-app-2 to Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'push'
#       - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-2:$SHORT_SHA'

# # List of Docker images to track
# images:
#   - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-1:$SHORT_SHA'
#   - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-2:$SHORT_SHA'

# # Build options and environment variables
# options:
#   env:
#     - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'

# # Logs bucket configuration
# logsBucket: ncorium-bucket

# Try to push image to a specific VM in 2 different folders
steps:
  # Build and push Docker image for app1
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-1:latest'
      - '-f'
      - 'app1/Dockerfile'
      - 'app1/'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-1:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh artifact-test \
        --zone=us-central1-a \
        --project=$PROJECT_ID \
        --command 'sudo su -c "cd / && mkdir folder1"'
        
  # SSH into GCE VM and copy app1 Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh artifact-test \
        --zone=us-central1-a \
        --project=$PROJECT_ID \
        --command 'sudo su -c "gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev && docker pull us-central1-docker.pkg.dev/nc-ev-test/test-application/flask-app-1:latest"

  # Build and push Docker image for app2
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-2:latest'
      - '-f'
      - 'app2/Dockerfile'
      - 'app2/'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-2:latest'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh artifact-test \
        --zone=us-central1-a \
        --project=$PROJECT_ID \
        --command 'sudo su -c "cd / && mkdir folder2"'
        
  # SSH into GCE VM and copy app2 Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh artifact-test \
        --zone=us-central1-a \
        --project=$PROJECT_ID \
        --command 'sudo su -c "gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev && docker pull us-central1-docker.pkg.dev/nc-ev-test/test-application/flask-app-2:latest" 

options:
  env:
    - 'LOGGING_OPTION=CLOUD_LOGGING_ONLY'
logsBucket: ncorium-bucket

