steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/[PROJECT_ID]/flask-app-1:${SHORT_SHA}'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/[PROJECT_ID]/flask-app-2:${SHORT_SHA}'
      - '-f'
      - 'Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-1:${SHORT_SHA}'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-application/flask-app-2:${SHORT_SHA}'
images:
  - 'gcr.io/[PROJECT_ID]/flask-app-1:${SHORT_SHA}'
  - 'gcr.io/[PROJECT_ID]/flask-app-2:${SHORT_SHA}'
